### ISSUE TITLE
Problem with exponent

### ISSUE THREAD

**Issue by franbanho** [marcingrzejszczak/jsonassert#31]
Hi guys,
I was using this library to test some json results and I found a very simple test case that is failing for me. Below you can see 2 different example, whereas the first one works fine, the second, which is very similar, it is just changing the exponent is failing.
By the way I am using version 0.4.13

1.-
 ` assertThatJson("{'n' : 1.12**E-6**}").field("n").isEqualTo(1.12**E-6**);` --> This works fine

2.-
  `assertThatJson("{'n' : 1.12**E-7**}").field("n").isEqualTo(1.12**E-7**);` -->This one does not work

The only difference is the exponent (you can see them in bold).
This is the stack trace I get:

```
`[ERROR] 2020-01-13 15:52:35.432 [main] JsonAsserter - Exception occurred while trying to match JSON Path [$[?(@.n == 1.12E-7)]]
com.jayway.jsonpath.InvalidPathException: Expected character: )
	at com.jayway.jsonpath.internal.CharacterIndex.readSignificantChar(CharacterIndex.java:218) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalANDOperand(FilterCompiler.java:185) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalAND(FilterCompiler.java:151) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.readLogicalOR(FilterCompiler.java:131) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:77) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.filter.FilterCompiler.compile(FilterCompiler.java:53) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readFilterToken(PathCompiler.java:461) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readNextToken(PathCompiler.java:141) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.readContextToken(PathCompiler.java:124) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:58) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.path.PathCompiler.compile(PathCompiler.java:75) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.JsonPath.<init>(JsonPath.java:101) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.JsonPath.compile(JsonPath.java:467) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:87) ~[json-path-2.4.0.jar:2.4.0]
	at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:96) ~[json-path-2.4.0.jar:2.4.0]
	at com.toomuchcoding.jsonassert.JsonAsserter.parseJsonPathAsArray(JsonAsserter.java:259) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.jsonPathToArray(JsonAsserter.java:254) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.check(JsonAsserter.java:226) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.checkBufferedJsonPathString(JsonAsserter.java:267) [jsonassert-0.4.13.jar:?]
	at com.toomuchcoding.jsonassert.JsonAsserter.isEqualTo(JsonAsserter.java:146) [jsonassert-0.4.13.jar:?]
```

Regards,
Fran

**Comment by marcingrzejszczak** [comment]
I think this an "issue" with Jayway JSONPath that we're using under the hood. As you can see we're just passing the JSON Path in the form of `$[?(@.n == 1.12E-7)]` to Jayway. You could either file an issue there but first check if it does indeed fail just by using plain Jayway.

**Comment by franbanho** [comment]
Hi, 
thanks for the quick response! Actually I am confused now since when I use JSON Path directly it does not work for any case, so I am not sure how you manage to make it work in the firsrt case. 

For me this line works (no exponents):

`JsonPath.read("{'n' : 1.12}", "$[?(@.n == 1.12)]");`

But this one, which worked with your library, here is not working, maybe I am doing something wrong

`JsonPath.read("{'n' : 1.12E-6}", "$[?(@.n == 1.12E-6)]");`
`assertThatJson("{'n' : 1.12E-6}").field("n").isEqualTo(1.12E-6);`

I can open a ticket to Jayway, but can you have a look into this case and check why it works with your library before I open a ticket to them?

Thanks

**Comment by franbanho** [comment]
Hi @marcingrzejszczak ,

I think the issue can be fixed by fixing the method 
`    String numberValue(Number number) {
        return new BigDecimal(number.toString()).toString();
    }`

I think this version will do the trick

`    String numberValue(Number number) {
        return new BigDecimal(number.toString()).**toPlainString()**;
    }`

Since the problem is that Jayway json path does not accept scientific notation you should call the method **toPlainString()** will not use it and I think it will work fine. Can you give it a try?

Thanks

**Comment by marcingrzejszczak** [comment]
I can, however, if you're interested you can file a pull request with a test and a fix for this. That way you will become a contributor :) What do you think?

**Comment by franbanho** [comment]
Sure! I give it a try! Thanks! :)

**Comment by franbanho** [comment]
Hi,
I created a pull request
[https://github.com/marcingrzejszczak/jsonassert/pull/32](https://github.com/marcingrzejszczak/jsonassert/pull/32)

**Comment by franbanho** [comment]
Hi @marcingrzejszczak ,
do you know when this fix will be available in Maven Central Repository?

**Comment by marcingrzejszczak** [comment]
Give me a second ;) I'm doing some house keeping and I'll release this shortly. Thanks for the PR!

**Comment by marcingrzejszczak** [comment]
Done 0.4.14 is in Central

**Comment by franbanho** [comment]
Great! Thanks! :)
